title: "Chazz Jordan"
author: "Chazz Jordan"
description: "currently @ the University of Georgia"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "about me",file: "/index.md", icon: home}
  - {title: "graduate research"}
  - {title: "research experiences"}
  - {title: "volunteering"}
  - {file: "/chazzjordan.pdf", title: "cv"}
  # - {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: want to email me?, url: "mailto:cmj93075@uga.edu"}
  - {title: my github site, url: "https://github.com/chazzjordan"}
 # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
